## Project - Foundations of Computer Science
### Bacchi Barbara - Matricola:  847401

### Academic Year: 2018/2019 
### Course: Data Science

In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
start = time.perf_counter() #Start the counter

Starting from the Google Play Store dataset

In [3]:
df = pd.read_csv('googleplaystore.csv')

Explore dataset

In [4]:
df.head() #to see the first few rows of DataFrame

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
df.info() #to see all columns with datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
App               10841 non-null object
Category          10841 non-null object
Rating            9367 non-null float64
Reviews           10841 non-null object
Size              10841 non-null object
Installs          10841 non-null object
Type              10840 non-null object
Price             10841 non-null object
Content Rating    10840 non-null object
Genres            10841 non-null object
Last Updated      10841 non-null object
Current Ver       10833 non-null object
Android Ver       10838 non-null object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [6]:
df.shape #to check the number of rows and columns

(10841, 13)

In [7]:
df.columns #The column labels of the DataFrame

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

#### Exercise 1. 
Convert the app sizes to a number

In [8]:
#Display the data type of each column
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [9]:
df['Size'].value_counts()

Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
191k                     1
511k                     1
872k                     1
658k                     1
270k                     1
Name: Size, Length: 462, dtype: int64

In [10]:
print("The variable Size has", df['Size'].isnull().sum(), "missing values")

The variable Size has 0 missing values

*I create two variables: one that contains the "numeric" part (e.g. 0, ... 9) and one that contains the "character" part (e.g. M, G, k, ..)*

In [11]:
df['num_size'] = df['Size'].str.extract('([0-9.]*[0-9]+)', expand=False).str.strip() 
df['type_size'] = df['Size'].str[-1]

In [12]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,num_size,type_size
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19,M
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14,M
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7,M
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25,M
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8,M

In [13]:
df['type_size'].value_counts()

M    8829
e    1695
k     316
+       1
Name: type_size, dtype: int64

*Let's examine what "e" and "+" represent*

In [14]:
df_e = df[df['type_size'] == 'e']
df_e['Size'].value_counts()

Varies with device    1695
Name: Size, dtype: int64

*For these records the variable does not return a correct value, therefore it is rightly managed as NaN*

In [15]:
df_plus = df[df['type_size'] == '+']
df_plus['Size'].value_counts()

1,000+    1
Name: Size, dtype: int64

*Not knowing the correct size of the record, this record will also be considered NaN*

In [16]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
num_size           object
type_size          object
dtype: object

In [17]:
df["num_size_float"]= df["num_size"].astype(float) #convert object in float number

In [18]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,num_size,type_size,num_size_float
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19,M,19.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14,M,14.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7,M,8.7
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25,M,25.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8,M,2.8

*I define the following function*

In [19]:
def string_to_number(row, unit):
    if row[unit] == 'G': #Giga
        return 1000000000
    if row[unit] == 'M': #Mega
        return 1000000
    if row[unit] == 'k': #kilo
        return 1000
    else:
        return np.nan #otherwise

In [20]:
df['type_size'] = df.apply(string_to_number, unit='type_size', axis=1)

*Let's check the numbers*

In [21]:
df.type_size.value_counts()

1000000.0    8829
1000.0        316
Name: type_size, dtype: int64

In [22]:
df.type_size.isnull().sum()

1696

*Let's create a new column for the converted data*

In [23]:
df['Size_num'] = df.num_size_float * df.type_size 
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,num_size,type_size,num_size_float,Size_num
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19,1000000.0,19.0,19000000.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14,1000000.0,14.0,14000000.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7,1000000.0,8.7,8700000.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25,1000000.0,25.0,25000000.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8,1000000.0,2.8,2800000.0

*I delete the columns that are no longer needed*

In [24]:
df.drop(columns=['num_size', 'type_size', 'num_size_float'], inplace = True)

In [25]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Size_num'],
      dtype='object')

#### Exercise 2. 
Convert the number of installs to a number

*Let's check the format of the variable "Installs"*

In [26]:
df['Installs'].value_counts()

1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
Free                 1
0                    1
Name: Installs, dtype: int64

In [27]:
print("The variable 'Installs' has", df['Installs'].isnull().sum(), "missing values")

The variable 'Installs' has 0 missing values

*I delete the "+" symbol and turn it into a number*

*I create two variables: one that contains the "numeric" part (e.g. 0, ... 9) and one that contains the "character" part (e.g. +)*

In [28]:
df['Installs_num'] = df['Installs'].str.extract('([0-9,]*[0-9]+)', expand=False).str.strip()
df['plus_symbol'] = df['Installs'].str.strip().str[-1]

In [29]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,plus_symbol
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19000000.0,"10,000",+
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14000000.0,"500,000",+
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8700000.0,"5,000,000",+
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25000000.0,"50,000,000",+
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2800000.0,"100,000",+

*Let's remove the comma*

In [30]:
df['Installs_num'] = df['Installs_num'].str.replace(',', '')

In [31]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,plus_symbol
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19000000.0,10000,+
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14000000.0,500000,+
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8700000.0,5000000,+
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25000000.0,50000000,+
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2800000.0,100000,+

*Check the only record that had the value of the variable equal to "Free"*

In [32]:
df[df['Installs'] == 'Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,plus_symbol
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,NaN,e

*Ok, It is NaN*

*Check the records that had the value of the variable equal to "0+"*

In [33]:
df[df['Installs'] == '0+']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,plus_symbol
4465,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5M,0+,Paid,$1.49,Everyone,Personalization,"July 11, 2018",1.1,4.2 and up,5500000.0,0,+
5307,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7M,0+,Paid,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up,8700000.0,0,+
5486,AP Series Solution Pro,FAMILY,NaN,0,7.4M,0+,Paid,$1.99,Everyone,Education,"July 30, 2017",1.3,4.0 and up,7400000.0,0,+
5945,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33M,0+,Paid,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up,33000000.0,0,+
6692,cronometra-br,PRODUCTIVITY,NaN,0,5.4M,0+,Paid,$154.99,Everyone,Productivity,"November 24, 2017",1.0.0,4.1 and up,5400000.0,0,+
7434,Pekalongan CJ,SOCIAL,NaN,0,5.9M,0+,Free,0,Teen,Social,"July 21, 2018",0.0.1,4.4 and up,5900000.0,0,+
8081,CX Network,BUSINESS,NaN,0,10M,0+,Free,0,Everyone,Business,"August 6, 2018",1.3.1,4.1 and up,10000000.0,0,+
8614,Sweden Newspapers,NEWS_AND_MAGAZINES,NaN,0,2.1M,0+,Free,0,Everyone,News & Magazines,"July 7, 2018",1.1,4.4 and up,2100000.0,0,+
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up,1200000.0,0,+
9337,EG | Explore Folegandros,TRAVEL_AND_LOCAL,NaN,0,56M,0+,Paid,$3.99,Everyone,Travel & Local,"January 22, 2017",1.1.1,4.1 and up,56000000.0,0,+
9719,EP Cook Book,MEDICAL,NaN,0,3.2M,0+,Paid,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up,3200000.0,0,+
9905,Eu sou Rico,FINANCE,NaN,0,2.6M,0+,Paid,$30.99,Everyone,Finance,"January 9, 2018",1.0,4.0 and up,2600000.0,0,+
9917,Eu Sou Rico,FINANCE,NaN,0,1.4M,0+,Paid,$394.99,Everyone,Finance,"July 11, 2018",1.0,4.0.3 and up,1400000.0,0,+
9934,I'm Rich/Eu sou Rico/أنا غني/我很有錢,LIFESTYLE,NaN,0,40M,0+,Paid,$399.99,Everyone,Lifestyle,"December 1, 2017",MONEY,4.1 and up,40000000.0,0,+

In [34]:
df['Installs_num'] = df['Installs_num'].astype(float) #convert the object in float number

In [35]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,plus_symbol
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19000000.0,10000.0,+
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14000000.0,500000.0,+
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8700000.0,5000000.0,+
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25000000.0,50000000.0,+
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2800000.0,100000.0,+

*I delete the columns that are no longer needed*

In [36]:
df.drop(columns=['plus_symbol'], inplace = True)

In [37]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Size_num', 'Installs_num'],
      dtype='object')

#### Exercize 3. 
Transform “Varies with device” into a missing value

In [38]:
df.replace('Varies with device', np.nan, inplace = True)

In [39]:
df[df['Size'] == 'Varies with device']

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver, Size_num, Installs_num]
Index: []

#### Exercise 4. 
Convert Current Ver and Android Ver into a dotted number (e.g. 4.0.3 or 4.2)

*Let's check the format of the variable "Current Ver"*

In [40]:
df['Current Ver'].value_counts()

1.0               809
1.1               264
1.2               178
2.0               151
1.3               145
                 ...
1.75                1
1.03.123.0713       1
4.1.11 - Hegoa      1
1.12.5.1            1
1.9.7.07            1
Name: Current Ver, Length: 2831, dtype: int64

In [41]:
print("The variable 'Current Ver' has", df['Current Ver'].isnull().sum(), "missing values")

The variable 'Current Ver' has 1467 missing values

*I extract the numbers in the format num.num.num*

In [42]:
df['Current_version'] = df['Current Ver'].str.extract('([0-9.]*[0-9])', expand=False).str.strip()

In [43]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19000000.0,10000.0,1.0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14000000.0,500000.0,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8700000.0,5000000.0,1.2.4
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2 and up,25000000.0,50000000.0,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2800000.0,100000.0,1.1

*Checking some non null Current Ver that were converted to NaN*

In [44]:
df[df.Current_version.isnull() & df['Current Ver'].notnull()][['App','Current Ver','Current_version']]

,App,Current Ver,Current_version
1423,Self Healing,Public.Heal,NaN
2501,HHS,Initial,NaN
3611,Latest Emmanuella Comedy Video,Natalia Studio Development,NaN
5218,AI Image Recognizer (beta),closed,NaN
5289,Ak-47 Wallpapers 2018,newversion,NaN
5981,BC iptv player,Final,NaN
7140,Cádiz CB Gades,opciÃ³n de cerrar,NaN
7509,App for Craigslist Pro - Buy & Sell Postings,App copyright,NaN
7510,Pro App for Craigslist,Copyright,NaN
7766,CR & CoC Private Server - Clash Barbarians PRO,Gratis,NaN
7997,CW Beacon for Ham Radio,KM,NaN
8435,DH-Security Camera,DH-Security Camera,NaN
8551,Auto DM for Twitter 🔥,HTTPs,NaN
9055,Human Dx,Human Dx,NaN
9322,EG Player,Final,NaN
9644,English to Hindi Dictionary,BlueOrange,NaN
9934,I'm Rich/Eu sou Rico/أنا غني/我很有錢,MONEY,NaN

*Let's check the format of the variable "Android Ver"*

In [45]:
df['Android Ver'].value_counts()

4.1 and up       2451
4.0.3 and up     1501
4.0 and up       1375
4.4 and up        980
2.3 and up        652
5.0 and up        601
4.2 and up        394
2.3.3 and up      281
2.2 and up        244
4.3 and up        243
3.0 and up        241
2.1 and up        134
1.6 and up        116
6.0 and up         60
7.0 and up         42
3.2 and up         36
2.0 and up         32
5.1 and up         24
1.5 and up         20
4.4W and up        12
3.1 and up         10
2.0.1 and up        7
8.0 and up          6
7.1 and up          3
5.0 - 8.0           2
1.0 and up          2
4.0.3 - 7.1.1       2
5.0 - 6.0           1
5.0 - 7.1.1         1
4.1 - 7.1.1         1
7.0 - 7.1.1         1
2.2 - 7.1.1         1
Name: Android Ver, dtype: int64

In [46]:
print("The variable 'Android Ver' has", df['Android Ver'].isnull().sum(), "missing values")

The variable 'Android Ver' has 1365 missing values

*Due to the data format, we transform the Android version in 2 different column a first version and a last version considering the 'and up' value as the latest version 10.0 of android today.*

In [47]:
df['Android_first'] = df['Android Ver'].str.extract('([0-9.]*[0-9])', expand=False).str.strip()

In [48]:
df['Android_last'] = df['Android Ver'].str.extract('([0-9.]*[0-9]$)', expand=False).str.strip()

In [49]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19000000.0,10000.0,1.0.0,4.0.3,NaN
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14000000.0,500000.0,2.0.0,4.0.3,NaN
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8700000.0,5000000.0,1.2.4,4.0.3,NaN
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2 and up,25000000.0,50000000.0,NaN,4.2,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2800000.0,100000.0,1.1,4.4,NaN

In [50]:
df_null = df[df['Android_last'].isnull()] #I filter the lines that do not have the latest version

In [51]:
df_null = df_null.drop(columns = ['Android_last']) #to avoid warning

In [52]:
df_notnull = df[df['Android_last'].notnull()] #I filter the lines that have the latest version

In [53]:
df_null['Android_last'] = df_null['Android Ver'].str.extract('([a-zA-Z\s]*[a-zA-Z\s])', expand=False).str.strip()

In [54]:
df_null['Android_last'].value_counts()

and up      9455
W and up      12
Name: Android_last, dtype: int64

In [55]:
df_null['Android_last'] = df_null['Android_last'].replace('and up','10.0')
df_null['Android_last'] = df_null['Android_last'].replace('W and up','10.0')

In [56]:
df = df_notnull.append(df_null) 
len(df) #to check the number of rows

10841

In [57]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
350,Web Browser & Explorer,COMMUNICATION,4.0,36901,6.6M,"5,000,000+",Free,0,Everyone,Communication,"July 4, 2018",11.8.6,4.0.3 - 7.1.1,6600000.0,5000000.0,11.8.6,4.0.3,7.1.1
352,Browser 4G,COMMUNICATION,4.3,192948,6.6M,"10,000,000+",Free,0,Everyone,Communication,"June 19, 2018",24.6.6,4.0.3 - 7.1.1,6600000.0,10000000.0,24.6.6,4.0.3,7.1.1
1572,ZenUI Safeguard,LIFESTYLE,4.5,100,7.1M,"1,000,000+",Free,0,Everyone,Lifestyle,"May 9, 2018",1.0.0.21_180410,7.0 - 7.1.1,7100000.0,1000000.0,1.0.0.21,7.0,7.1.1
2841,Photo Collage - Layout Editor,PHOTOGRAPHY,4.5,285788,46M,"10,000,000+",Free,0,Everyone,Photography,"December 4, 2017",1.8.0.170824_9,5.0 - 8.0,46000000.0,10000000.0,1.8.0.170824,5.0,8.0
3474,ASUS Quick Memo,PRODUCTIVITY,4.5,23089,1.6M,"10,000,000+",Free,0,Everyone,Productivity,"April 11, 2018",1.10.0.33_180403,5.0 - 8.0,1600000.0,10000000.0,1.10.0.33,5.0,8.0

#### Exercise 5. 
Remove the duplicates

*Verify if the App column has unique value*

In [58]:
if df['App'].nunique == df.shape[0]:
    print("The # of unique App is equal to # of rows")
else:
    print("The App is not a unique identifier!")

The App is not a unique identifier!

In [59]:
duplicates = df[df.duplicated(subset='App')]
print("Of the %s total Apps, %s are duplicated" % (len(df), len(df[df.duplicated(subset='App')])))

Of the 10841 total Apps, 1181 are duplicated

In [60]:
#Dropping duplicates which have every value in common
df.drop_duplicates(inplace=True)

In [61]:
len(df)

10358

In [62]:
print(len(df[df.duplicated(subset='App')]), "duplicated projects remain.")
duplicated = df[df.duplicated(subset='App', keep=False)].sort_values(by='App')
duplicated.head(10)

698 duplicated projects remain.

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
5415,365Scores - Live Scores,SPORTS,4.6,666246,25M,"10,000,000+",Free,0,Everyone,Sports,"July 29, 2018",5.5.9,4.1 and up,25000000.0,10000000.0,5.5.9,4.1,10.0
3083,365Scores - Live Scores,SPORTS,4.6,666521,25M,"10,000,000+",Free,0,Everyone,Sports,"July 29, 2018",5.5.9,4.1 and up,25000000.0,10000000.0,5.5.9,4.1,10.0
1755,8 Ball Pool,GAME,4.5,14200344,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
1703,8 Ball Pool,GAME,4.5,14198602,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
1871,8 Ball Pool,GAME,4.5,14201891,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
1844,8 Ball Pool,GAME,4.5,14200550,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
1675,8 Ball Pool,GAME,4.5,14198297,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
1970,8 Ball Pool,GAME,4.5,14201604,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
3953,8 Ball Pool,SPORTS,4.5,14184910,52M,"100,000,000+",Free,0,Everyone,Sports,"July 31, 2018",4.0.0,4.0.3 and up,52000000.0,100000000.0,4.0.0,4.0.3,10.0
559,95Live -SG#1 Live Streaming App,DATING,4.1,4953,15M,"1,000,000+",Free,0,Teen,Dating,"August 1, 2018",8.7.2,4.2 and up,15000000.0,1000000.0,8.7.2,4.2,10.0

*Get list of index for duplicated Apps*

In [63]:
dup_ids = duplicated['App'].unique()
for i in dup_ids:
    index1 = duplicated[duplicated.App == i][:1].index.values
    index2 = duplicated[duplicated.App == i][1:2].index.values
    print(index1, index2)

[5415] [3083]
[1755] [1703]
[559] [662]
[4991] [920]
[4928] [3799]
[3791] [5448]
[2771] [2800]
[5512] [3628]
[1143] [1095]
[3895] [3452]
[2814] [2936]
[3880] [1947]
[3215] [3116]
[2790] [2756]
[5075] [2982]
[2549] [10171]
[3936] [1933]
[143] [4083]
[3922] [2664]
[2654] [5353]
[3158] [5952]
[2571] [9853]
[1938] [4252]
[4864] [1843]
[1990] [3883]
[1665] [1984]
[5223] [2237]
[3508] [3548]
[1448] [1509]
[8667] [3378]
[2816] [2859]
[2980] [3089]
[6449] [406]
[674] [488]
[7055] [1075]
[717] [796]
[6203] [3425]
[2588] [6546]
[1687] [2045]
[6914] [3404]
[6054] [2862]
[1991] [1850]
[6450] [1244]
[539] [580]
[6673] [3050]
[3952] [1746]
[1883] [1719]
[2001] [1672]
[2310] [2513]
[6587] [2323]
[2881] [6212]
[3156] [3112]
[1907] [1720]
[5910] [3178]
[1657] [2041]
[1979] [1686]
[755] [3988]
[3056] [2976]
[2675] [7446]
[4949] [413]
[3513] [5611]
[7544] [3293]
[3360] [7537]
[3343] [7539]
[9840] [1132]
[2218] [8193]
[941] [7988]
[3239] [8894]
[477] [3242]
[436] [206]
[440] [8305]
[1340] [1438]
[1286] [1386]
[1397] [1411]
[6652] [2913]
[2890] [5042]
[6654] [2905]
[2828] [8126]
[2949] [2911]
[1980] [2015]
[2909] [2944]
[1688] [1985]
[3994] [1655]
[1668] [1716]
[1077] [1169]
[1535] [6679]
[5044] [2269]
[3702] [7582]
[1790] [7501]
[532] [574]
[3189] [7240]
[2156] [9641]
[3926] [1195]
[5595] [1853]
[576] [517]
[7329] [3456]
[7353] [360]
[3987] [1660]
[1670] [1879]
[825] [4089]
[6989] [1771]
[1003] [3915]
[2033] [1]
[1892] [1707]
[564] [505]
[3989] [751]
[7455] [1074]
[7106] [3084]
[1919] [4040]
[933] [910]
[197] [7939]
[1698] [1986]
[2865] [2935]
[8246] [315]
[8250] [2124]
[1936] [2009]
[5728] [1934]
[1942] [5433]
[8202] [1840]
[8901] [424]
[312] [6411]
[1209] [8714]
[2639] [4718]
[568] [515]
[2374] [4374]
[3976] [1574]
[9621] [145]
[2063] [7613]
[2029] [2091]
[8785] [2192]
[4056] [1902]
[3569] [4048]
[1931] [8670]
[8412] [1868]
[1189] [8746]
[784] [8439]
[4075] [1135]
[3970] [2371]
[4072] [3514]
[2959] [4069]
[2986] [3045]
[1927] [1978]
[9628] [820]
[1289] [1387]
[6296] [186]
[707] [6305]
[9689] [1786]
[2123] [9314]
[3482] [4084]
[3102] [3129]
[2967] [3082]
[2379] [10730]
[8174] [2811]
[2544] [3943]
[10203] [215]
[4105] [2546]
[201] [10200]
[1845] [10190]
[1733] [1695]
[514] [10715]
[2095] [2052]
[575] [511]
[2923] [10118]
[5381] [1826]
[344] [412]
[358] [10720]
[1895] [1683]
[3871] [3292]
[3819] [3755]
[2698] [4101]
[4989] [2668]
[541] [679]
[1744] [1681]
[905] [10018]
[2974] [3069]
[670] [508]
[697] [512]
[8440] [2591]
[9680] [2138]
[1741] [1904]
[2209] [10502]
[852] [4301]
[3566] [4160]
[3446] [4809]
[1684] [1896]
[726] [9589]
[1894] [1690]
[1915] [1718]
[3265] [3326]
[4141] [1696]
[451] [340]
[4150] [3234]
[4979] [238]
[401] [410]
[3476] [3533]
[338] [411]
[824] [791]
[3528] [3477]
[3523] [3454]
[3121] [9841]
[9844] [3816]
[3458] [8320]
[1083] [5601]
[2808] [2884]
[5856] [865]
[3526] [8458]
[3232] [3127]
[3235] [3907]
[5594] [359]
[2554] [4144]
[4148] [1679]
[9842] [2716]
[4200] [870]
[4185] [1583]
[6562] [953]
[924] [9826]
[2895] [2919]
[6919] [3405]
[386] [464]
[9856] [384]
[1803] [1846]
[1792] [1918]
[1658] [2026]
[829] [844]
[590] [524]
[6626] [2508]
[1689] [1977]
[1743] [1992]
[664] [485]
[1474] [9982]
[1256] [9975]
[1888] [1808]
[3104] [3183]
[2093] [2057]
[6288] [491]
[3212] [5623]
[3210] [3111]
[1456] [1496]
[938] [8029]
[9574] [2251]
[1758] [1988]
[6579] [1930]
[903] [888]
[1863] [8433]
[2858] [2825]
[2941] [2870]
[2545] [2604]
[4368] [1350]
[1621] [1601]
[4249] [2007]
[5531] [1852]
[663] [518]
[1048] [4287]
[4302] [407]
[6845] [1671]
[1745] [8195]
[2104] [3902]
[952] [7606]
[2869] [8307]
[4724] [297]
[403] [4122]
[1800] [4327]
[758] [3999]
[703] [807]
[793] [832]
[950] [927]
[2582] [2621]
[4320] [2565]
[4325] [1753]
[8261] [1851]
[1801] [8268]
[3495] [4355]
[5620] [3062]
[3005] [3095]
[4365] [3703]
[1899] [1676]
[325] [5905]
[6882] [3869]
[3117] [3223]
[8138] [3826]
[2148] [9671]
[8727] [1176]
[2111] [23]
[579] [535]
[530] [596]
[6293] [2593]
[2641] [2585]
[1816] [1855]
[2547] [10170]
[4106] [339]
[335] [382]
[1960] [8187]
[4086] [380]
[3527] [3459]
[3463] [3567]
[3550] [3532]
[3457] [4087]
[3486] [3530]
[3934] [3522]
[566] [521]
[4347] [2241]
[4036] [1694]
[1117] [6304]
[9359] [1713]
[4987] [3302]
[6286] [489]
[476] [571]
[1097] [1148]
[1146] [9839]
[2136] [2214]
[719] [2113]
[3865] [5516]
[9821] [3233]
[3670] [10647]
[2231] [9343]
[2120] [9361]
[2837] [8446]
[1697] [1890]
[1908] [1722]
[2963] [3074]
[6509] [162]
[6497] [146]
[3777] [5544]
[958] [3889]
[2791] [6251]
[2628] [2613]
[6086] [2226]
[1312] [9854]
[1319] [1281]
[6577] [2917]
[2054] [881]
[194] [293]
[3120] [9859]
[483] [6302]
[5062] [2850]
[415] [356]
[417] [4421]
[2772] [5545]
[2316] [2489]
[9642] [155]
[3913] [1673]
[714] [4804]
[9440] [2038]
[4232] [2642]
[1794] [1847]
[1194] [8751]
[1076] [1156]
[747] [2240]
[1357] [2344]
[8347] [2578]
[9529] [2876]
[8442] [2576]
[2933] [2873]
[2921] [2897]
[2861] [2916]
[2930] [7003]
[2924] [2864]
[2938] [4448]
[4088] [2552]
[2003] [1911]
[1881] [1706]
[5610] [2109]
[2207] [955]
[10646] [3760]
[3908] [1764]
[1662] [1885]
[3701] [4300]
[10178] [2983]
[705] [2025]
[372] [5505]
[6643] [3455]
[285] [222]
[7572] [2855]
[4501] [2579]
[1748] [2088]
[1818] [5294]
[8309] [2012]
[9143] [2239]
[8424] [894]
[3783] [5474]
[1913] [1732]
[3400] [5606]
[790] [801]
[1486] [7570]
[1788] [8194]
[1308] [1298]
[1277] [1323]
[1439] [5600]
[4566] [3255]
[2646] [2614]
[1206] [8725]
[1207] [8747]
[2624] [2596]
[1709] [1897]
[7937] [1932]
[3272] [4748]
[4610] [954]
[2955] [2802]
[1260] [4854]
[3148] [3109]
[294] [240]
[10753] [2765]
[3437] [3372]
[2610] [2603]
[4051] [1699]
[2024] [1973]
[4235] [1667]
[9570] [157]
[1197] [8754]
[2734] [2718]
[1943] [2115]
[9936] [2059]
[3896] [1654]
[1884] [1674]
[1996] [1926]
[6294] [700]
[2594] [2644]
[4239] [387]
[893] [4211]
[1906] [4321]
[2598] [2625]
[2794] [2697]
[370] [392]
[4747] [2558]
[1661] [1886]
[4238] [2586]
[5392] [2589]
[4241] [42]
[10269] [3000]
[921] [7987]
[2710] [4090]
[9494] [3186]
[9569] [1831]
[9779] [942]
[5384] [1848]
[2127] [3920]
[853] [2151]
[3504] [8640]
[1876] [1752]
[4588] [3738]
[1712] [1877]
[1742] [1976]
[3825] [5964]
[3136] [3115]
[4602] [449]
[1510] [1465]
[858] [932]
[4586] [2599]
[2119] [4261]
[889] [4589]
[4115] [3739]
[420] [378]
[419] [4633]
[7027] [36]
[4634] [3827]
[925] [974]
[4681] [3675]
[3956] [3325]
[467] [342]
[8535] [3667]
[5774] [3712]
[3671] [5704]
[3686] [4686]
[971] [878]
[3531] [4720]
[945] [4076]
[1273] [1380]
[139] [4715]
[3820] [4717]
[4742] [2616]
[390] [4712]
[3662] [9568]
[10026] [423]
[1299] [1318]
[1379] [1288]
[1073] [1168]
[1217] [8744]
[4727] [367]
[3904] [336]
[363] [393]
[10213] [2561]
[8450] [441]
[4102] [2712]
[1715] [1882]
[1765] [1889]
[3502] [3546]
[3042] [3009]
[4800] [345]
[3382] [4793]
[2833] [2922]
[2945] [2849]
[3665] [3928]
[4805] [891]
[2014] [859]
[3684] [4796]
[2493] [2320]
[2942] [4824]
[3354] [4031]
[1627] [1633]
[4821] [2636]
[1237] [1255]
[4244] [1898]
[1874] [1728]
[1730] [3940]
[482] [7077]
[3445] [5863]
[835] [9635]
[2662] [4068]
[789] [743]
[4224] [389]
[383] [347]
[2663] [4322]
[525] [673]
[4593] [3492]
[2331] [6194]
[2595] [2618]
[10473] [3334]
[1468] [5664]
[1757] [1891]
[565] [499]
[2637] [2590]
[2964] [3055]
[3652] [8291]

*Some examples*

In [64]:
df.loc[5415] == df.loc[3083]

App                 True
Category            True
Rating              True
Reviews            False
Size                True
Installs            True
Type                True
Price               True
Content Rating      True
Genres              True
Last Updated        True
Current Ver         True
Android Ver         True
Size_num            True
Installs_num        True
Current_version     True
Android_first       True
Android_last        True
dtype: bool

In [65]:
df.loc[3922] == df.loc[2664]

App                 True
Category            True
Rating              True
Reviews            False
Size                True
Installs            True
Type                True
Price               True
Content Rating      True
Genres              True
Last Updated        True
Current Ver         True
Android Ver         True
Size_num            True
Installs_num        True
Current_version     True
Android_first       True
Android_last        True
dtype: bool

In [66]:
df.loc[3880] == df.loc[1947]

App                 True
Category            True
Rating              True
Reviews            False
Size                True
Installs            True
Type                True
Price               True
Content Rating      True
Genres              True
Last Updated        True
Current Ver         True
Android Ver         True
Size_num            True
Installs_num        True
Current_version     True
Android_first       True
Android_last        True
dtype: bool

*The variable that generates duplicates is Reviews*

*First of all, we sort the dataset according to the App and Review in descending order, and then we drop the duplicates keeping only the first value.*

In [67]:
df.sort_values(by=['App', 'Reviews'], ascending=[False, False], inplace = True)

In [68]:
df.drop_duplicates('App',keep='first', inplace = True)

In [69]:
duplicates = df[df.duplicated(subset='App')]
print("Of the %s total Apps, %s are duplicated" % (len(df), len(df[df.duplicated(subset='App')])))

Of the 9660 total Apps, 0 are duplicated

*Reset the index and create a new index*

In [70]:
df = df.reset_index().drop('index',axis = 1)
df.index.name="AppId"
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
AppId,,,,,,,,,,,,,,,,,,
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,ENTERTAINMENT,4.7,11661,4.0M,"1,000,000+",Free,0,Everyone,Entertainment,"July 14, 2018",1.1.3.2,4.0.3 and up,4000000.0,1000000.0,1.1.3.2,4.0.3,10.0
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,TOOLS,4.0,19,3.2M,"10,000+",Free,0,Everyone,Tools,"October 21, 2017",1.0,4.2 and up,3200000.0,10000.0,1.0,4.2,10.0
2,"💘 WhatsLov: Smileys of love, stickers and GIF",SOCIAL,4.6,22098,18M,"1,000,000+",Free,0,Everyone,Social,"July 24, 2018",4.2.4,4.0.3 and up,18000000.0,1000000.0,4.2.4,4.0.3,10.0
3,💎 I'm rich,LIFESTYLE,3.8,718,26M,"10,000+",Paid,$399.99,Everyone,Lifestyle,"March 11, 2018",1.0.0,4.4 and up,26000000.0,10000.0,1.0.0,4.4,10.0
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",VIDEO_PLAYERS,NaN,414,59M,"100,000+",Free,0,Mature 17+,Video Players & Editors,"July 18, 2018",4.0.7,4.0.3 and up,59000000.0,100000.0,4.0.7,4.0.3,10.0

#### Exercise 6. 
For each category, compute the number of apps

In [71]:
df['Category'].value_counts().sort_index()

1.9                       1
ART_AND_DESIGN           61
AUTO_AND_VEHICLES        85
BEAUTY                   53
BOOKS_AND_REFERENCE     222
BUSINESS                420
COMICS                   56
COMMUNICATION           315
DATING                  171
EDUCATION               108
ENTERTAINMENT            87
EVENTS                   64
FAMILY                 1876
FINANCE                 345
FOOD_AND_DRINK          112
GAME                    943
HEALTH_AND_FITNESS      288
HOUSE_AND_HOME           73
LIBRARIES_AND_DEMO       84
LIFESTYLE               369
MAPS_AND_NAVIGATION     131
MEDICAL                 395
NEWS_AND_MAGAZINES      254
PARENTING                60
PERSONALIZATION         376
PHOTOGRAPHY             281
PRODUCTIVITY            374
SHOPPING                202
SOCIAL                  239
SPORTS                  325
TOOLS                   828
TRAVEL_AND_LOCAL        219
VIDEO_PLAYERS           164
WEATHER                  79
Name: Category, dtype: int64

#### Exercise 7. 
For each category, compute the average rating

*We've seen that there is an anomalous value*

In [72]:
df[df['Category'] == '1.9']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
AppId,,,,,,,,,,,,,,,,,,
3853,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,NaN,4.0,NaN,NaN

*I've decided to delete that value*

In [73]:
df = df[df.Category != '1.9']

In [74]:
df.groupby('Category').agg({'Rating':'mean'})

                       Rating
Category
ART_AND_DESIGN       4.359322
AUTO_AND_VEHICLES    4.190411
BEAUTY               4.278571
BOOKS_AND_REFERENCE  4.344970
BUSINESS             4.098479
COMICS               4.181481
COMMUNICATION        4.121484
DATING               3.970149
EDUCATION            4.358879
ENTERTAINMENT        4.129885
EVENTS               4.435556
FAMILY               4.183525
FINANCE              4.115563
FOOD_AND_DRINK       4.171277
GAME                 4.243527
HEALTH_AND_FITNESS   4.243033
HOUSE_AND_HOME       4.140984
LIBRARIES_AND_DEMO   4.178125
LIFESTYLE            4.093355
MAPS_AND_NAVIGATION  4.036441
MEDICAL              4.166552
NEWS_AND_MAGAZINES   4.121569
PARENTING            4.300000
PERSONALIZATION      4.332215
PHOTOGRAPHY          4.157414
PRODUCTIVITY         4.183389
SHOPPING             4.230556
SOCIAL               4.247291
SPORTS               4.216154
TOOLS                4.039917
TRAVEL_AND_LOCAL     4.069519
VIDEO_PLAYERS        4.044966
WEATHER              4.243056

### Exercise 8. 
Create two dataframes: one for the genres and one bridging apps and genres.
So that, for instance, the app Pixel Draw - Number Art Coloring Book appears twice in the bridging table, once for Art & Design, once for Creativity

*I create the first dataframe with genres*

In [75]:
df['Genres'].value_counts()

Tools                                827
Entertainment                        561
Education                            510
Business                             420
Medical                              395
                                    ...
Entertainment;Education                1
Board;Pretend Play                     1
Arcade;Pretend Play                    1
Parenting;Brain Games                  1
Travel & Local;Action & Adventure      1
Name: Genres, Length: 119, dtype: int64

*We have genres that have ";" therefore they are to be separated*

In [76]:
genres_list = list(df['Genres'])

In [77]:
genres_new = []
for genre in genres_list:
    genre_split = genre.split(";")
    genres_new.extend(genre_split)

In [78]:
df_genres = pd.DataFrame(genres_new, columns = ['Genres'])

In [79]:
df_genres['Genres'].value_counts()

Tools                      828
Education                  678
Entertainment              592
Business                   420
Medical                    395
Personalization            376
Productivity               374
Lifestyle                  370
Finance                    345
Sports                     335
Communication              316
Action                     311
Health & Fitness           290
Photography                281
News & Magazines           254
Social                     239
Books & Reference          225
Casual                     224
Travel & Local             219
Simulation                 206
Shopping                   202
Arcade                     199
Dating                     171
Video Players & Editors    165
Puzzle                     143
Maps & Navigation          131
Role Playing               115
Food & Drink               112
Racing                     108
Educational                102
Strategy                    99
Action & Adventure          98
Auto & Vehicles             85
Libraries & Demo            84
Adventure                   80
Weather                     79
House & Home                73
Pretend Play                69
Brain Games                 66
Art & Design                65
Events                      64
Parenting                   60
Board                       60
Comics                      56
Beauty                      53
Card                        49
Trivia                      39
Casino                      39
Creativity                  33
Music & Video               31
Word                        23
Music                       22
Music & Audio                1
Name: Genres, dtype: int64

In [80]:
df_genres['Genres'].unique()

array(['Entertainment', 'Tools', 'Social', 'Lifestyle',
       'Video Players & Editors', 'Comics', 'Education',
       'Books & Reference', 'Communication', 'Maps & Navigation',
       'House & Home', 'Shopping', 'Simulation', 'Adventure',
       'Art & Design', 'Strategy', 'News & Magazines', 'Auto & Vehicles',
       'Action', 'Finance', 'Food & Drink', 'Arcade', 'Weather',
       'Personalization', 'Educational', 'Events', 'Medical',
       'Travel & Local', 'Sports', 'Casual', 'Puzzle', 'Dating',
       'Business', 'Productivity', 'Photography', 'Beauty',
       'Health & Fitness', 'Libraries & Demo', 'Casino', 'Parenting',
       'Trivia', 'Music & Video', 'Racing', 'Action & Adventure',
       'Creativity', 'Card', 'Board', 'Pretend Play', 'Word',
       'Brain Games', 'Role Playing', 'Music & Audio', 'Music'],
      dtype=object)

In [81]:
df_genres.drop_duplicates(inplace = True)

In [82]:
df_genres = df_genres.reset_index(drop=True)

*I create the Genres_Id (key of the table)*

In [83]:
df_genres['Genres_Id'] = df_genres.index

In [84]:
df_genres.head()

                    Genres  Genres_Id
0            Entertainment          0
1                    Tools          1
2                   Social          2
3                Lifestyle          3
4  Video Players & Editors          4

*I create the first dataframe with genres and app*

In [85]:
df_app = df[['App','Genres']]

In [86]:
df_app['Genres'].value_counts()

Tools                                827
Entertainment                        561
Education                            510
Business                             420
Medical                              395
                                    ...
Entertainment;Education                1
Board;Pretend Play                     1
Arcade;Pretend Play                    1
Parenting;Brain Games                  1
Travel & Local;Action & Adventure      1
Name: Genres, Length: 119, dtype: int64

In [87]:
df_app[df_app.duplicated('App',keep=False)]

Empty DataFrame
Columns: [App, Genres]
Index: []

In [88]:
df_app = df_app.reset_index(drop=True)

*I create the App_Id (key of the table)*

In [89]:
df_app['App_Id'] = df_app.index

In [90]:
df_app.head()

,App,Genres,App_Id
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,Entertainment,0
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,Tools,1
2,"💘 WhatsLov: Smileys of love, stickers and GIF",Social,2
3,💎 I'm rich,Lifestyle,3
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",Video Players & Editors,4

In [91]:
df_app = df_app.assign(Genres = df.Genres.str.split(';')).explode('Genres')

In [92]:
df_app = df_app.reset_index(drop=True)

In [93]:
df_app.head()

,App,Genres,App_Id
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,Entertainment,0
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,Tools,1
2,"💘 WhatsLov: Smileys of love, stickers and GIF",Social,2
3,💎 I'm rich,Lifestyle,3
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",Video Players & Editors,4

*Create a bridging table*

In [94]:
df_app.columns

Index(['App', 'Genres', 'App_Id'], dtype='object')

In [95]:
df_genres.columns

Index(['Genres', 'Genres_Id'], dtype='object')

In [96]:
bridging_table = pd.merge(df_app,df_genres, on = 'Genres').sort_values('App_Id')

In [97]:
bridging_table.head()

,App,Genres,App_Id,Genres_Id
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,Entertainment,0,0
592,📏 Smart Ruler ↔️ cm/inch measuring for homework!,Tools,1,1
1420,"💘 WhatsLov: Smileys of love, stickers and GIF",Social,2,2
1659,💎 I'm rich,Lifestyle,3,3
2029,"뽕티비 - 개인방송, 인터넷방송, BJ방송",Video Players & Editors,4,4

*Checking if there are any duplicates*

In [98]:
bridging_table[bridging_table.duplicated('App_Id',keep=False)].sort_values('App_Id').head()

                               App       Genres  App_Id  Genres_Id
2260       iTooch Mathématiques CP    Education     157          6
2261       iTooch Mathématiques CP    Education     157          6
2267  codeSpark Academy & The Foos    Education     277          6
6088  codeSpark Academy & The Foos  Educational     277         24
2274                      Zowi App    Education     353          6

In [99]:
df_app[df_app['App'] == 'iTooch Mathématiques CP']

                         App     Genres  App_Id
157  iTooch Mathématiques CP  Education     157
158  iTooch Mathématiques CP  Education     157

In [100]:
df[df['App'] == 'iTooch Mathématiques CP']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_num,Installs_num,Current_version,Android_first,Android_last
AppId,,,,,,,,,,,,,,,,,,
157,iTooch Mathématiques CP,FAMILY,4.3,1018,35M,"100,000+",Free,0,Everyone,Education;Education,"June 28, 2017",4.6.2,4.0.3 and up,35000000.0,100000.0,4.6.2,4.0.3,10.0

*We see that the Genre Education is somehow duplicated in different Apps (iTooch Mathématiques CP) that is because of the format of original dataframe, in the Genres column it has two times Education!*

*Remove the duplicated rows*

In [101]:
bridging_table.drop_duplicates(inplace=True)

*Checking again if there are still some duplicates*

In [102]:
bridging_table.duplicated().any()

False

### Exercise 9. 
For each genre, create a new column of the original dataframe. The new columns must have boolean values (True if the app has a given genre)

In [103]:
df['Genres'].value_counts()

Tools                                827
Entertainment                        561
Education                            510
Business                             420
Medical                              395
                                    ...
Entertainment;Education                1
Board;Pretend Play                     1
Arcade;Pretend Play                    1
Parenting;Brain Games                  1
Travel & Local;Action & Adventure      1
Name: Genres, Length: 119, dtype: int64

In [104]:
df = df.assign(Genres_split = df.Genres.str.split(';')).explode('Genres_split')

In [105]:
df['Genres'] = df['Genres_split'] #Create a copy of this variable for get_dummies

In [106]:
df.shape

(10054, 19)

*I create the dummy variables*

In [107]:
df = pd.get_dummies(df, columns=['Genres_split'])

In [108]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Genres_split_Simulation,Genres_split_Social,Genres_split_Sports,Genres_split_Strategy,Genres_split_Tools,Genres_split_Travel & Local,Genres_split_Trivia,Genres_split_Video Players & Editors,Genres_split_Weather,Genres_split_Word
AppId,,,,,,,,,,,,,,,,,,,,,
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,ENTERTAINMENT,4.7,11661,4.0M,"1,000,000+",Free,0,Everyone,Entertainment,...,0,0,0,0,0,0,0,0,0,0
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,TOOLS,4.0,19,3.2M,"10,000+",Free,0,Everyone,Tools,...,0,0,0,0,1,0,0,0,0,0
2,"💘 WhatsLov: Smileys of love, stickers and GIF",SOCIAL,4.6,22098,18M,"1,000,000+",Free,0,Everyone,Social,...,0,1,0,0,0,0,0,0,0,0
3,💎 I'm rich,LIFESTYLE,3.8,718,26M,"10,000+",Paid,$399.99,Everyone,Lifestyle,...,0,0,0,0,0,0,0,0,0,0
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",VIDEO_PLAYERS,NaN,414,59M,"100,000+",Free,0,Mature 17+,Video Players & Editors,...,0,0,0,0,0,0,0,1,0,0

In [109]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Size_num', 'Installs_num', 'Current_version',
       'Android_first', 'Android_last', 'Genres_split_Action',
       'Genres_split_Action & Adventure', 'Genres_split_Adventure',
       'Genres_split_Arcade', 'Genres_split_Art & Design',
       'Genres_split_Auto & Vehicles', 'Genres_split_Beauty',
       'Genres_split_Board', 'Genres_split_Books & Reference',
       'Genres_split_Brain Games', 'Genres_split_Business',
       'Genres_split_Card', 'Genres_split_Casino', 'Genres_split_Casual',
       'Genres_split_Comics', 'Genres_split_Communication',
       'Genres_split_Creativity', 'Genres_split_Dating',
       'Genres_split_Education', 'Genres_split_Educational',
       'Genres_split_Entertainment', 'Genres_split_Events',
       'Genres_split_Finance', 'Genres_split_Food & Drink',
       'Genres_split_Health & Fitness', 'Genres_split_House & Home',
       'Genres_split_Libraries & Demo', 'Genres_split_Lifestyle',
       'Genres_split_Maps & Navigation', 'Genres_split_Medical',
       'Genres_split_Music', 'Genres_split_Music & Audio',
       'Genres_split_Music & Video', 'Genres_split_News & Magazines',
       'Genres_split_Parenting', 'Genres_split_Personalization',
       'Genres_split_Photography', 'Genres_split_Pretend Play',
       'Genres_split_Productivity', 'Genres_split_Puzzle',
       'Genres_split_Racing', 'Genres_split_Role Playing',
       'Genres_split_Shopping', 'Genres_split_Simulation',
       'Genres_split_Social', 'Genres_split_Sports', 'Genres_split_Strategy',
       'Genres_split_Tools', 'Genres_split_Travel & Local',
       'Genres_split_Trivia', 'Genres_split_Video Players & Editors',
       'Genres_split_Weather', 'Genres_split_Word'],
      dtype='object')

In [110]:
list_col = []
for col in df.columns:
    if col.startswith('Genres_split_'):
        list_col.append(col)

In [111]:
df_dummy = df[df.columns & list_col]

In [112]:
df_dummy = df_dummy.replace(0,False)

In [113]:
df_dummy = df_dummy.replace(1,True)

In [114]:
for col in list_col:
    if col in df.columns:
        df.drop([col], axis = 'columns', inplace = True)
    else:
        print(col, "is not found")

In [115]:
df.shape

(10054, 18)

In [116]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Size_num', 'Installs_num', 'Current_version',
       'Android_first', 'Android_last'],
      dtype='object')

In [117]:
df = pd.concat([df, df_dummy], axis=1, sort=False)

In [118]:
df.shape

(10054, 71)

In [119]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Genres_split_Simulation,Genres_split_Social,Genres_split_Sports,Genres_split_Strategy,Genres_split_Tools,Genres_split_Travel & Local,Genres_split_Trivia,Genres_split_Video Players & Editors,Genres_split_Weather,Genres_split_Word
AppId,,,,,,,,,,,,,,,,,,,,,
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,ENTERTAINMENT,4.7,11661,4.0M,"1,000,000+",Free,0,Everyone,Entertainment,...,False,False,False,False,False,False,False,False,False,False
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,TOOLS,4.0,19,3.2M,"10,000+",Free,0,Everyone,Tools,...,False,False,False,False,True,False,False,False,False,False
2,"💘 WhatsLov: Smileys of love, stickers and GIF",SOCIAL,4.6,22098,18M,"1,000,000+",Free,0,Everyone,Social,...,False,True,False,False,False,False,False,False,False,False
3,💎 I'm rich,LIFESTYLE,3.8,718,26M,"10,000+",Paid,$399.99,Everyone,Lifestyle,...,False,False,False,False,False,False,False,False,False,False
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",VIDEO_PLAYERS,NaN,414,59M,"100,000+",Free,0,Mature 17+,Video Players & Editors,...,False,False,False,False,False,False,False,True,False,False

### Exercise 10. 
For each genre, compute the average rating. What is the genre with highest average?

In [120]:
df['Rating'].isnull().sum()

1477

In [121]:
avg_rating_bygenre = pd.DataFrame(df.groupby('Genres').agg({'Rating':'mean'}))

In [122]:
avg_rating_bygenre

                           Rating
Genres
Action                   4.247697
Action & Adventure       4.288542
Adventure                4.191026
Arcade                   4.277838
Art & Design             4.350000
Auto & Vehicles          4.190411
Beauty                   4.278571
Board                    4.287719
Books & Reference        4.343275
Brain Games              4.358462
Business                 4.098479
Card                     4.076087
Casino                   4.286486
Casual                   4.139352
Comics                   4.181481
Communication            4.121790
Creativity               4.306250
Dating                   3.970149
Education                4.290630
Educational              4.100000
Entertainment            4.093028
Events                   4.435556
Finance                  4.115563
Food & Drink             4.171277
Health & Fitness         4.243496
House & Home             4.140984
Libraries & Demo         4.178125
Lifestyle                4.094040
Maps & Navigation        4.036441
Medical                  4.166552
Music                    4.219048
Music & Audio            4.300000
Music & Video            4.229032
News & Magazines         4.121569
Parenting                4.300000
Personalization          4.332215
Photography              4.157414
Pretend Play             4.238235
Productivity             4.183389
Puzzle                   4.370968
Racing                   4.174757
Role Playing             4.272072
Shopping                 4.230556
Simulation               4.154500
Social                   4.247291
Sports                   4.225185
Strategy                 4.227368
Tools                    4.039917
Travel & Local           4.069519
Trivia                   4.039286
Video Players & Editors  4.044667
Weather                  4.243056
Word                     4.318182

In [123]:
print("The Genre with highest average is", avg_rating_bygenre.idxmax())

The Genre with highest average is Rating    Events
dtype: object

### Exercise 11. 
For each app, compute the approximate income, obtain as a product of number of installs and price.

In [124]:
print("The variable 'Price' has", df['Price'].isnull().sum(), "missing values")

The variable 'Price' has 0 missing values

In [125]:
df['Price'].value_counts()

0          9228
$2.99       151
$0.99       150
$1.99        80
$4.99        79
           ...
$15.46        1
$4.80         1
$3.95         1
$154.99       1
$3.61         1
Name: Price, Length: 92, dtype: int64

In [126]:
df['Price_value'] = df['Price'].str.extract('([0-9.]*[0-9]+)', expand=False).str.strip()

In [127]:
df['Price_value_float'] = df['Price_value'].astype(float)

In [128]:
df['approximate_income'] = df.Installs_num * df.Price_value_float

In [129]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Genres_split_Strategy,Genres_split_Tools,Genres_split_Travel & Local,Genres_split_Trivia,Genres_split_Video Players & Editors,Genres_split_Weather,Genres_split_Word,Price_value,Price_value_float,approximate_income
AppId,,,,,,,,,,,,,,,,,,,,,
0,🔥 Football Wallpapers 4K | Full HD Backgrounds 😍,ENTERTAINMENT,4.7,11661,4.0M,"1,000,000+",Free,0,Everyone,Entertainment,...,False,False,False,False,False,False,False,0,0.00,0.0
1,📏 Smart Ruler ↔️ cm/inch measuring for homework!,TOOLS,4.0,19,3.2M,"10,000+",Free,0,Everyone,Tools,...,False,True,False,False,False,False,False,0,0.00,0.0
2,"💘 WhatsLov: Smileys of love, stickers and GIF",SOCIAL,4.6,22098,18M,"1,000,000+",Free,0,Everyone,Social,...,False,False,False,False,False,False,False,0,0.00,0.0
3,💎 I'm rich,LIFESTYLE,3.8,718,26M,"10,000+",Paid,$399.99,Everyone,Lifestyle,...,False,False,False,False,False,False,False,399.99,399.99,3999900.0
4,"뽕티비 - 개인방송, 인터넷방송, BJ방송",VIDEO_PLAYERS,NaN,414,59M,"100,000+",Free,0,Mature 17+,Video Players & Editors,...,False,False,False,False,True,False,False,0,0.00,0.0

*I delete the columns that are no longer needed*

In [130]:
df.drop(columns=['Price_value', 'Price_value_float'], inplace = True)

### Exercise 12

For each app, compute its minimum and maximum Sentiment_polarity

In [131]:
df_review = pd.read_csv('googleplaystore_user_reviews.csv')

In [132]:
df_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [133]:
df_review.isna().any()

App                       False
Translated_Review          True
Sentiment                  True
Sentiment_Polarity         True
Sentiment_Subjectivity     True
dtype: bool

In [134]:
df_sentimentpol = df_review.groupby('App').agg({'Sentiment_Polarity': [min, max]})

In [135]:
df_sentimentpol.head()

                                 Sentiment_Polarity
                                                min       max
App
10 Best Foods for You                       -0.8000  1.000000
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室            -0.1125  0.910000
11st                                        -1.0000  1.000000
1800 Contacts - Lens Store                  -0.3000  0.838542
1LINE – One Line with One Touch             -0.8250  1.000000

In [136]:
end = time.perf_counter() #Stop the counter

In [137]:
print("CPU time", "%.2f" %(end - start))

CPU time 4.92